import type { Metadata } from "next";
import {  Albert_Sans, } from "next/font/google";
import "./globals.css";


const albertSans = Albert_Sans({
  variable: "--font-albert-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${albertSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
